### ISSUE TITLE
notes.map is not a function 

### ISSUE THREAD

**Issue by rahulsrivastava1** [CodeWithHarry/iNotebook-React#6]
After adding `auth-token= localStorage.getItem('token')` in noteState.js
I got an error called notes.map is not a function in `notes.js`.
and if I leave auth-token="hardcoded auth-token" then its working?

How to fix it?
@CodeWithHarry bhaiya ... your app worked in the video but not mine. I got an error.

**Comment by WindingSnow** [comment]
Post a screenshot of your code  @rahulsrivastava1

**Comment by rahulsrivastava1** [comment]
Showing error
![error](https://user-images.githubusercontent.com/54400720/133475112-b379a7e7-eb0a-4c80-a21f-6ed78da315e1.png)

When I changed auth-token ="hard coded" to auth-token=localStorage.getItem("token"); then i got error
![changed](https://user-images.githubusercontent.com/54400720/133475279-9b5166dd-4a5f-408f-8790-d32f92cc7f79.png)

Error found here and code
![error found here](https://user-images.githubusercontent.com/54400720/133475319-75f72d34-aaef-42d3-85ef-e11968ea0cd7.png)

**Comment by rahulsrivastava1** [comment]
@Saarthak-Slathia check !

**Comment by pranayb13** [comment]
Even I got the same error and came to github for the commit... What is the error here ? Can somebody help...?

**Comment by WindingSnow** [comment]
Just check that have you declared **notesInitial** as an empty array in NoteState.js file as the **.map** method works only with arrays. 

`const notesInitial = [];`

**Comment by pranayb13** [comment]
I have done that still the issue persist...!! what do i do

**Comment by rahulsrivastava1** [comment]
Already used as discussed in videos @Saarthak-Slathia . Can @CodeWithHarry bhaiya just commit that final commit of this project?
![used](https://user-images.githubusercontent.com/54400720/133608065-1c4ddc1f-51bb-40af-9e95-e68b1d2fb99b.png)

**Comment by WindingSnow** [comment]
@rahulsrivastava1 You can compare your code with mine and just check what is causing the issue. The link to my repository is https://github.com/Saarthak-Slathia/iNotebook

_Note: I have made some changes in my code such as adding a Landing page etc. You can make changes in your application as per your need_

**Comment by rahulsrivastava1** [comment]
@Saarthak-Slathia ok bro! I will check it out! Hope my app will start working :)

**Comment by Mr-Robot001** [comment]
@rahulsrivastava1  bro if you get this error solution please share because  i am also facing it ......

**Comment by rahulsrivastava1** [comment]
@Mr-Robot001 ok sure! Let me check first. I was busy today ... i will check tomorrow.

**Comment by rahulsrivastava1** [comment]
@Saarthak-Slathia bro everything is same, but not running. How your app is running? @Mr-Robot001 bro problem is not gone!

**Comment by rahulsrivastava1** [comment]
@Saarthak-Slathia I completely copy your noteState.js and notes.js, even then it is showing the same error. any system issue?

**Comment by rahulsrivastava1** [comment]
@pranayb13 did your problem resolve?

**Comment by WindingSnow** [comment]
@rahulsrivastava1 can you just send me the link of your project repository ? I will try to check what is causing the issue.

**Comment by Mr-Robot001** [comment]
@Mr-Robot001 bro problem is not gone!

@rahulsrivastava1 okay bro

**Comment by rahulsrivastava1** [comment]
@Saarthak-Slathia sure bro! but I didn't upload it in GitHub because it is not finalized. Can I share with you the zip file? or I push code in repo and give you the link... whatever you want?

**Comment by WindingSnow** [comment]
@rahulsrivastava1 You can push the code temporarily on Github because that would be easier to check. You can push the final commit of the code once the project would finalize.

**Comment by rahulsrivastava1** [comment]
@Saarthak-Slathia bro here it is , https://github.com/rahulsrivastava1/iNoteBook/tree/master

**Comment by WindingSnow** [comment]
@rahulsrivastava1 I have solved the problem, you had not defined the success variable properly in the auth.js file and there were few more small errors that I have fixed. You can go to your iNotebook repository page and merge the pull request opened by me with the name **Error Solved: Notes.map is not a function.**

**Comment by rahulsrivastava1** [comment]
@Saarthak-Slathia ok i am checking...thank you bro so much🔥

**Comment by rahulsrivastava1** [comment]
@Saarthak-Slathia bro app is still showing errors!

**Comment by rahulsrivastava1** [comment]
![error](https://user-images.githubusercontent.com/54400720/134164461-f40136ff-10ae-4e15-a122-5cbf96f5e8d1.png)

**Comment by WindingSnow** [comment]
Have you checked the latest commit? If yes, then if the error is coming instantly after starting the application, just delete all the users from the database manually and then try again by sign up or login. Maybe it will help

**Comment by rahulsrivastava1** [comment]
Ok i am doing

**Comment by rahulsrivastava1** [comment]
@Saarthak-Slathia how to merge master into main

**Comment by rahulsrivastava1** [comment]
@Saarthak-Slathia yes checked ,app doesn't start right  now same problem ,i also cleaeed database but nothing affects... please check once again!

**Comment by WindingSnow** [comment]
@rahulsrivastava1 But on my computer, the code is working perfectly fine 🤔

**Comment by rahulsrivastava1** [comment]
@Saarthak-Slathia it means my laptop has an issue. Some days ago, I completely changed my code to your but that also didn't work.

**Comment by rahulsrivastava1** [comment]
@Saarthak-Slathia one thing more if I want to clone your codes then from where I can find node_modules because node_modules are not in Github. How did you run mine code?

**Comment by WindingSnow** [comment]
> @Saarthak-Slathia one thing more if I want to clone your codes then from where I can find node_modules because node_modules are not in Github. How did you run mine code?

You can type `npm install` in the terminal. It will automatically install all the required modules.

**Comment by rahulsrivastava1** [comment]
ok @Saarthak-Slathia , first I will be checking my app from fresh and then your, if that also does not work, it means my pc has an issue.

**Comment by Mr-Robot001** [comment]
I think this is not a  problem of pc....
I think This problem with our API limit. If we have any limits for our
custom API then we have to face this type of error..

**Comment by rahulsrivastava1** [comment]
@Saarthak-Slathia your app is running absolutely perfectly fine, but not mine. I will check someday when I will be free.

Amazing project, by the way, loved your app. Did you know react before this tutorial?

**Comment by rahulsrivastava1** [comment]
@Mr-Robot001 yeah bro you are right... Can we change the api?

**Comment by rahulsrivastava1** [comment]
@Mr-Robot001 bro thank you so much, I changed API and it works. @Saarthak-Slathia thanks for your help, you tried all possible things. @pranayb13 change your api .

**Comment by WindingSnow** [comment]
> @Mr-Robot001 bro thank you so much, I changed API and it works. @Saarthak-Slathia thanks for your help, you tried all possible things. @pranayb13 change your api .

Welcome and yes I knew basic react before this course, by the way, is the react course over/finished?

**Comment by rahulsrivastava1** [comment]
@Saarthak-Slathia no-no the course is not over.

**Comment by WindingSnow** [comment]
> @Saarthak-Slathia no-no the course is not over.

okay thanks 👍🏻

**Comment by Prathik-reddy** [comment]
@rahulsrivastava1 which api did u changed?

**Comment by rahulsrivastava1** [comment]
@Prathik-reddy mongo db compass..just change database name inotebook to other

**Comment by Prathik-reddy** [comment]
> @Prathik-reddy mongo db compass..just change database name inotebook to other

@rahulsrivastava1 ty bro for ur help

**Comment by Prathik-reddy** [comment]
@rahulsrivastava1 I did changed the database name but it didn't worked out for me . Could you be more specific about in which file did you changed the db name.

**Comment by rahulsrivastava1** [comment]
> @rahulsrivastava1 I did changed the database name but it didn't worked out for me . Could you be more specific about in which file did you changed the db name. 

db.js in backend, if that doesn't work create another string in database and paste it here

**Comment by S-G-Codes** [comment]
> After adding `auth-token= localStorage.getItem('token')` in noteState.js
> I got an error called notes.map is not a function in `notes.js`.
> and if I leave auth-token="hardcoded auth-token" then its working?
> 
> How to fix it?
> @CodeWithHarry bhaiya ... your app worked in the video but not mine. I got an error.

Bro I am also getting the same error I tried all the things mentioned on this topic still cant figure out please any one help! 
My token is still undefined in application and error is same map. is not a function 
please Help Guys

**Comment by Prathik-reddy** [comment]
@S-G-Codes Same here I also tried everything mentioned over here  but none worked out for me .Stuck on this issue since few days 😔.

**Comment by S-G-Codes** [comment]
> @S-G-Codes Same here I also tried everything mentioned over here but none worked out for me .Stuck on this issue since few days 😔.




Same bro its getting irritated now! @rahulsrivastava1 @CodeWithHarry  @Saarthak-Slathia  this guy's can only help us

**Comment by rahulsrivastava1** [comment]
> > After adding `auth-token= localStorage.getItem('token')` in noteState.js
> > I got an error called notes.map is not a function in `notes.js`.
> > and if I leave auth-token="hardcoded auth-token" then its working?
> > How to fix it?
> > @CodeWithHarry bhaiya ... your app worked in the video but not mine. I got an error.
> 
> Bro I am also getting the same error I tried all the things mentioned on this topic still cant figure out please any one help! My token is still undefined in application and error is same map. is not a function please Help Guys

hey @S-G-Codes @prathik please follow above replies

**Comment by WindingSnow** [comment]
@S-G-Codes Can you send your GitHub code repository as it would be easier to check what's causing the error? before that, just check that have you imported all the imports properly because the **notes.map** function would only work if **notes** is an array if it is undefined due to an import error, it will not work.

**Comment by Prathik-reddy** [comment]
@Saarthak-Slathia Could you pls have a look at my code too ,I am also getting the same error:notes.map is not a function

**Comment by WindingSnow** [comment]
> @Saarthak-Slathia Could you pls have a look at my code too,I am also getting the same error:notes.map is not a function

Yes, I will, Just send me the link to your repository. I will try my best to resolve the issue

**Comment by Prathik-reddy** [comment]
> > @Saarthak-Slathia Could you pls have a look at my code too,I am also getting the same error:notes.map is not a function
> 
> Yes, I will, Just send me the link to your repository. I will try my best to resolve the issue

@Saarthak-Slathia 
[Link to my iNoteBook repo](https://github.com/Prathik-reddy/iNoteBook) 
Hope u solve this error 👨‍💻🙂

**Comment by WindingSnow** [comment]
@Prathik-reddy I think your application has no errors, I tried it but there were no errors. The only problem was that you didn't add the logout button and the logout function which I have fixed. Probably, you can try changing your database name and path in the db.js file in the backend directory. To see the changes I have made, you can go to your iNotebook repository page and merge the pull request created by me.

**Comment by Prathik-reddy** [comment]
@Saarthak-Slathia I have tried changing the db name and path a couple of times infact I deleted the whole database and started from scratch but it didn't worked out for me.And talking about the merging part I will surely do it as soon as possible and let u know about further updates.Thanks for ur help🤝.

**Comment by S-G-Codes** [comment]
> @S-G-Codes Can you send your GitHub code repository as it would be easier to check what's causing the error? before that, just check that have you imported all the imports properly because the **notes.map** function would only work if **notes** is an array if it is undefined due to an import error, it will not work.



https://github.com/S-G-Codes/inotebook    this is my repo and I am new to git so I may have messed up the files hope you'll understand and also for now  I have hard coded the auth token and also I have created a new database so no api limit issue in short I have tried all the above comments but still same error occurs your help  would be really appreciated! @Saarthak-Slathia  @rahulsrivastava1 I did all the above sol but still error exit!

**Comment by rahulsrivastava1** [comment]
https://github.com/rahulsrivastava1/iNoteBook check it out @S-G-Codes

**Comment by aksinghdbg** [comment]
> After adding `auth-token= localStorage.getItem('token')` in noteState.js I got an error called notes.map is not a function in `notes.js`. and if I leave auth-token="hardcoded auth-token" then its working?
> 
> How to fix it? @CodeWithHarry bhaiya ... your app worked in the video but not mine. I got an error.

**Comment by aksinghdbg** [comment]
check the spelling of authtoken in backend

**Comment by harshvarmora28** [comment]
@rahulsrivastava1 bro can you tell me, how you got this error fixed? I am facing this issue from 2 days 😕

**Comment by harshvarmora28** [comment]
@Saarthak-Slathia @rahulsrivastava1 guys please help me to find the solution of error (notes.map is not a function), look into my github repo ( https://github.com/harshvarmora28/keep_notes_react_website ) for the same.

**Comment by rahulsrivastava1** [comment]
@harshvarmora28 in my case , api got exhausted

**Comment by harshvarmora28** [comment]
@rahulsrivastava1 So now what's the solution? When will the api get back to work?

**Comment by rahulsrivastava1** [comment]
@harshvarmora28 just delete existing API and create a new one

**Comment by harshvarmora28** [comment]
> @harshvarmora28 just delete existing API and create a new one

Ok 🙂, I will try.

**Comment by Tausif-H6** [comment]
> > @harshvarmora28 just delete existing API and create a new one
> 
> Ok 🙂, I will try.



> @Mr-Robot001 bro thank you so much, I changed API and it works. @Saarthak-Slathia thanks for your help, you tried all possible things. @pranayb13 change your api .

const response = await fetch(`${host}/api/notes/fetchallnotes`, did you change this API? I have the same error too but I am confused if you deleted this API then which API you use to fetch the user data?

**Comment by harshvarmora28** [comment]
> > > @harshvarmora28 just delete existing API and create a new one
> > 
> > Ok 🙂, I will try.
> 
> 
> 
> > @Mr-Robot001 bro thank you so much, I changed API and it works. @Saarthak-Slathia thanks for your help, you tried all possible things. @pranayb13 change your api .
> 
> const response = await fetch(`${host}/api/notes/fetchallnotes`, did you change this API? I have the same error too but I am confused if you deleted this API then which API you use to fetch the user data?

Yes bro, I changed it but nothing worked for me too. Let's wait for harry bhai to commit his final code 🥲

**Comment by yashgarg4** [comment]
> After adding `auth-token= localStorage.getItem('token')` in noteState.js I got an error called notes.map is not a function in `notes.js`. and if I leave auth-token="hardcoded auth-token" then its working?
> 
> How to fix it? @CodeWithHarry bhaiya ... your app worked in the video but not mine. I got an error.

bro can u help me fix this error!!...I am stuck on this  from last 2 days..plz help me out..

**Comment by rahulsrivastava1** [comment]
@yashgarg4, I changed API it worked for me, my API got exhausted.

**Comment by harshvarmora28** [comment]
> @yashgarg4, I changed API it worked for me, my API got exhausted.

bhai can you explain me where to change the API? I mean how can API exhaust, cause we are not using any external API like in previous project (news app)...

**Comment by harshvarmora28** [comment]
@rahulsrivastava1 just copy and paste the line of code where you changed the API and it worked for you😅.

**Comment by vipulchaudhary16** [comment]
You can check my repo ! I had completed the project and it's running correctly

**Comment by harshvarmora28** [comment]
@S-G-Codes @Prathik-reddy @ho699 @yashgarg4 @rahulsrivastava1 I got a solution of the error ( notes.map() is not a function ), simply change the spelling of ( authtoken to authToken ) in the Login and SignUp component where you are setting the authToken using localStorage.setItem(), please look into attached image to find out exactly where to change for the fix😅😎. 

![image](https://user-images.githubusercontent.com/82329898/140338007-6c89264c-d0f6-4f97-a9e6-44e1edfb0915.png)

**Comment by rahulsrivastava1** [comment]
Great! @harshvarmora28

**Comment by Tausif-H6** [comment]
> @S-G-Codes @Prathik-reddy @ho699 @yashgarg4 @rahulsrivastava1 I got a solution of the error ( notes.map() is not a function ), simply change the spelling of ( authtoken to authToken ) in the Login and SignUp component where you are setting the authToken using localStorage.setItem(), please look into attached image to find out exactly where to change for the fix😅😎.
> 
> ![image](https://user-images.githubusercontent.com/82329898/140338007-6c89264c-d0f6-4f97-a9e6-44e1edfb0915.png)

Brother made the changes according to yours but still getting the same error.

**Comment by vipulchaudhary16** [comment]
> > @S-G-Codes @Prathik-reddy @ho699 @yashgarg4 @rahulsrivastava1 I got a solution of the error ( notes.map() is not a function ), simply change the spelling of ( authtoken to authToken ) in the Login and SignUp component where you are setting the authToken using localStorage.setItem(), please look into attached image to find out exactly where to change for the fix😅😎.
> > ![image](https://user-images.githubusercontent.com/82329898/140338007-6c89264c-d0f6-4f97-a9e6-44e1edfb0915.png)
> 
> Brother made the changes according to yours but still getting the same error.

go to inspect **Console -> Application**  and see there that is token undefined? or it's a token which we had hardcoded before changing it to **LocalStorage.getItem('token')**

**Comment by Tausif-H6** [comment]
> > > @S-G-Codes @Prathik-reddy @ho699 @yashgarg4 @rahulsrivastava1 I got a solution of the error ( notes.map() is not a function ), simply change the spelling of ( authtoken to authToken ) in the Login and SignUp component where you are setting the authToken using localStorage.setItem(), please look into attached image to find out exactly where to change for the fix😅😎.
> > > ![image](https://user-images.githubusercontent.com/82329898/140338007-6c89264c-d0f6-4f97-a9e6-44e1edfb0915.png)
> > 
> > 
> > Brother made the changes according to yours but still getting the same error.
> 
> go to inspect **Console -> Application** and see there that is token undefined? or it's a token which we had hardcoded before changing it to **LocalStorage.getItem('token')**



> > > @S-G-Codes @Prathik-reddy @ho699 @yashgarg4 @rahulsrivastava1 I got a solution of the error ( notes.map() is not a function ), simply change the spelling of ( authtoken to authToken ) in the Login and SignUp component where you are setting the authToken using localStorage.setItem(), please look into attached image to find out exactly where to change for the fix😅😎.
> > > ![image](https://user-images.githubusercontent.com/82329898/140338007-6c89264c-d0f6-4f97-a9e6-44e1edfb0915.png)
> > 
> > 
> > Brother made the changes according to yours but still getting the same error.
> 
> go to inspect **Console -> Application** and see there that is token undefined? or it's a token which we had hardcoded before changing it to **LocalStorage.getItem('token')**

I already did that but still error.

![g2](https://user-images.githubusercontent.com/78949436/140695072-4837f415-8162-40f9-af6b-3b7f09bafddd.JPG)
![g1](https://user-images.githubusercontent.com/78949436/140695075-a3a7f1e8-0e6e-40e3-8a3f-f3dc6da15969.JPG)

**Comment by Tausif-H6** [comment]
![g3](https://user-images.githubusercontent.com/78949436/140695398-b564e29f-1aca-4a4d-ab4c-a70ba1769060.JPG)
![g2](https://user-images.githubusercontent.com/78949436/140695406-de6e3b64-6213-40e4-acb8-3a05e85d191c.JPG)
![g1](https://user-images.githubusercontent.com/78949436/140695408-2d48ba45-51ef-43e0-90d2-b098bcaf6b39.JPG)
How to fix this error!!?

**Comment by harshvarmora28** [comment]
@ho699 please, check logging the token once by console.log(json.authToken) and see if token appears their...

**Comment by Tausif-H6** [comment]
> @ho699 please, check logging the token once by console.log(json.authToken) and see if token appears their...

In the backend file token working perfectly but token is not appearing at console.
![g4](https://user-images.githubusercontent.com/78949436/140697605-e2f15084-52bc-45e5-a453-29b4ee9d8944.JPG)

**Comment by harshvarmora28** [comment]
> > @ho699 please, check logging the token once by console.log(json.authToken) and see if token appears their...
> 
> In the backend file token working perfectly but token is not appearing at console. ![g4](https://user-images.githubusercontent.com/78949436/140697605-e2f15084-52bc-45e5-a453-29b4ee9d8944.JPG)

this means you have to find out the correct spelling of authToken which you used in backend and replace it in the frontend, that's the problem i guess...

**Comment by Tausif-H6** [comment]
> > > @ho699 please, check logging the token once by console.log(json.authToken) and see if token appears their...
> > 
> > 
> > In the backend file token working perfectly but token is not appearing at console. ![g4](https://user-images.githubusercontent.com/78949436/140697605-e2f15084-52bc-45e5-a453-29b4ee9d8944.JPG)
> 
> this means you have to find out the correct spelling of authToken which you used in backend and replace it in the frontend, that's the problem i guess...

No I followed exactly what harry bhai did.

**Comment by S-G-Codes** [comment]
> ![g3](https://user-images.githubusercontent.com/78949436/140695398-b564e29f-1aca-4a4d-ab4c-a70ba1769060.JPG) ![g2](https://user-images.githubusercontent.com/78949436/140695406-de6e3b64-6213-40e4-acb8-3a05e85d191c.JPG) ![g1](https://user-images.githubusercontent.com/78949436/140695408-2d48ba45-51ef-43e0-90d2-b098bcaf6b39.JPG) How to fix this error!!?

@ho699  Bro just check the endpoints name once like its createUser or createuser check all the endpoints name from everywhere right from auth, thunderclient where you are making the the request  and also check where are you fetching the user or anything. I hope this help.

**Comment by krcpr007** [comment]
> Showing error ![error](https://user-images.githubusercontent.com/54400720/133475112-b379a7e7-eb0a-4c80-a21f-6ed78da315e1.png)
> 
> When I changed auth-token ="hard coded" to auth-token=localStorage.getItem("token"); then i got error ![changed](https://user-images.githubusercontent.com/54400720/133475279-9b5166dd-4a5f-408f-8790-d32f92cc7f79.png)
> 
> Error found here and code ![error found here](https://user-images.githubusercontent.com/54400720/133475319-75f72d34-aaef-42d3-85ef-e11968ea0cd7.png)



> After adding `auth-token= localStorage.getItem('token')` in noteState.js I got an error called notes.map is not a function in `notes.js`. and if I leave auth-token="hardcoded auth-token" then its working?
> 
> How to fix it? @CodeWithHarry bhaiya ... your app worked in the video but not mine. I got an error.

Hii guys many of you are probably facing "notes.map is not function error ", Here I have a solution for you guys, and it's working !!

what you have to do is go to the NoteState.js replace"auth-token": localStorage.getItem('auth-token'); at four places!!
it means you have to replace "token" with "auth-token" everywhere like LoginJs Signup.js Navbar.js NoteState.js, Notes.js !!
also replace this localStorage.setItem('token', json.authtoken); with this localStorage.setItem('auth-token', json.authToken); wherever you used !!
I hope this will help you all guys !!
Happy coding <3

**Comment by antimabhatra23** [comment]
> @S-G-Codes @Prathik-reddy @ho699 @yashgarg4 @rahulsrivastava1 I got a solution of the error ( notes.map() is not a function ), simply change the spelling of ( authtoken to authToken ) in the Login and SignUp component where you are setting the authToken using localStorage.setItem(), please look into attached image to find out exactly where to change for the fix😅😎.
> 
> ![image](https://user-images.githubusercontent.com/82329898/140338007-6c89264c-d0f6-4f97-a9e6-44e1edfb0915.png)

**Comment by antimabhatra23** [comment]
I also got the same error and check all the things. What should I do, Please someone suggest. I have another error also that is when I hardcode my database connection URL then It'll work but when I use without hardcode it'll not work and I'll try to use all the things.

**Comment by vipulchaudhary16** [comment]
> I also got the same error and check all the things. What should I do, Please someone suggest. I have another error also that is when I hardcode my database connection URL then It'll work but when I use without hardcode it'll not work and I'll try to use all the things.

problem 1: notes.map is not a function
solution: notes variable is undefined while fetching this issue has occurred 

problem 2: hard code link issue
solution: try to use the environment variable https://www.dhiwise.com/post/react-environment-variables-your-guide-to-secure-react-apps
