### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by haseebkhalid907** [CodeWithHarry/iNotebook-React#7]
![Screen Shot 2021-09-15 at 6 03 44 PM](https://user-images.githubusercontent.com/72162790/133787797-545443d9-335e-44eb-bb26-33a5929ef524.png)
[](url)

**Comment by haseebkhalid907** [comment]
how To solve this issue?

**Comment by haseebkhalid907** [comment]
anybody can help me

**Comment by WindingSnow** [comment]
@haseebkhalid907 can you provide some more information such as where the error is occurring ?
